apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecretsconfig.yaml
  - networkpolicy-egress.yaml
  - clustersecretstore.yaml
  - cluster-externalsecrets.yaml
