apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: gitlab
  name: gitlab-oidc-config
type: Opaque
stringData:
  OIDC_ISSUER: ""
  OIDC_CLIENT_ID: gitlab
  OIDC_CLIENT_SECRET: ""
  OIDC_REDIRECT_URI: ""
