apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gitlab-runner
  name: gitlab-runner-auth
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
stringData:
  token: {{ .Values.gitlab.runner.token | default "pending" | quote }}
