apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: console-user
  namespace: kafka
  labels:
    strimzi.io/cluster: rhads-kafka
    app.kubernetes.io/part-of: rhads-demo
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations: [Read, Describe, DescribeConfigs]
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations: [Read]
      - resource:
          type: cluster
        operations: [Describe, DescribeConfigs]
