apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - namespace-console.yaml
  - kafka-metrics-config.yaml
  - kafka.yaml
  - topics.yaml
  - kafka-user-console.yaml
  - console.yaml
  - kafka-exporter-monitor.yaml
