apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhtpa-operator
  namespace: trusted-profile-analyzer
  labels:
    app.kubernetes.io/part-of: rhads-demo
spec:
  channel: stable-v3
  installPlanApproval: Automatic
  name: rhtpa-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
