apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: stackrox
  labels:
    app.kubernetes.io/part-of: rhads-demo
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  clusterName: devopsdays
  scanner:
    scannerComponent: AutoSense
  perNode:
    collector:
      collection: CORE_BPF
