apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
  labels:
    app.kubernetes.io/part-of: rhads-demo
    app: vault
data:
  vault.hcl: |
    ui = true
    disable_mlock = true
    listener "tcp" {
      address = "[::]:8200"
      tls_disable = 1
    }
    storage "file" {
      path = "/vault/data"
    }
    api_addr = "http://vault.vault.svc:8200"
    cluster_addr = "http://vault.vault.svc:8201"
