apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app.kubernetes.io/part-of: rhads-demo
    app: vault
spec:
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vault
  namespace: vault
  labels:
    app.kubernetes.io/part-of: rhads-demo
    app: vault
spec:
  host: vault.CLUSTER_SUBDOMAIN_PLACEHOLDER
  to:
    kind: Service
    name: vault
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
