apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
stringData:
  username: keycloak
  password: keycloak
  database: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: keycloak
type: Opaque
stringData:
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: keycloak
  POSTGRES_DB: keycloak
