---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
  description: Application developers
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineers
  description: Platform engineers
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dev1
spec:
  profile:
    displayName: Developer One
    email: dev1@rhads.demo
  memberOf: [developers]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dev2
spec:
  profile:
    displayName: Developer Two
    email: dev2@rhads.demo
  memberOf: [developers]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dev3
spec:
  profile:
    displayName: Developer Three
    email: dev3@rhads.demo
  memberOf: [developers]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: pe1
spec:
  profile:
    displayName: Platform Engineer One
    email: pe1@rhads.demo
  memberOf: [platform-engineers]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: pe2
spec:
  profile:
    displayName: Platform Engineer Two
    email: pe2@rhads.demo
  memberOf: [platform-engineers]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: pe3
spec:
  profile:
    displayName: Platform Engineer Three
    email: pe3@rhads.demo
  memberOf: [platform-engineers]
