{{- if .Values.maas.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "quarkus-template.name" . }}-maas
  labels:
    {{- include "quarkus-template.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "quarkus-template.name" . }}-maas
    creationPolicy: Owner
  data:
    - secretKey: MAAS_API_KEY
      remoteRef:
        key: apps/{{ include "quarkus-template.name" . }}
        property: MAAS_API_KEY
    - secretKey: MAAS_BASE_URL
      remoteRef:
        key: apps/{{ include "quarkus-template.name" . }}
        property: MAAS_BASE_URL
    - secretKey: MAAS_MODEL
      remoteRef:
        key: apps/{{ include "quarkus-template.name" . }}
        property: MAAS_MODEL
{{- end }}
