apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "quarkus-template.name" . }}
  labels:
    {{- include "quarkus-template.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "quarkus-template.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /q/metrics
      interval: 30s
