apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdc.name" . }}-db-credentials
  labels:
    {{- include "cdc.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
  POSTGRES_DB: {{ .Values.db.name | quote }}
  database.user: {{ .Values.db.user | quote }}
  database.password: {{ .Values.db.password | quote }}
  database.dbname: {{ .Values.db.name | quote }}
