apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-devspaces
resources:
  - namespace.yaml
  - container-build-scc.yaml
  - checluster.yaml
  - devworkspace-container-build-rbac.yaml
  - vscode-editor-configurations.yaml
  - image-prefetch.yaml
