apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trusted-profile-analyzer
resources:
  - namespace.yaml
  - postgresql-rbac.yaml
  - secrets.yaml
  - postgresql.yaml
  - storage-pvc.yaml
  - rhda-backend.yaml
  - job-patch-rhda-oidc.yaml
  - cronjob-analyze.yaml
