apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: trusted-profile-analyzer
type: Opaque
stringData:
  db.host: tpa-postgresql
  db.port: "5432"
  db.name: rhtpadb
  db.user: tpa
  db.password: tpa-demo-password
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-admin-credentials
  namespace: trusted-profile-analyzer
type: Opaque
stringData:
  db.host: tpa-postgresql
  db.port: "5432"
  db.name: rhtpadb
  db.user: postgres
  db.password: tpa-demo-admin
