apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  namespace: trusted-profile-analyzer
  labels:
    app.kubernetes.io/part-of: rhads-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi