apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - uiplugin-monitoring.yaml
  - perses-datasource.yaml
  - perses-dashboard-kafka.yaml
  - perses-dashboard-apps.yaml
  - perses-dashboard-cdc.yaml
  - rbac.yaml
