apiVersion: perses.dev/v1alpha1
kind: PersesDatasource
metadata:
  name: prometheus-rhads
  namespace: rhads-observability
  labels:
    app.kubernetes.io/part-of: rhads-demo
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  config:
    default: true
    plugin:
      kind: PrometheusDatasource
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
            tlsConfig:
              insecureSkipVerify: true
